const mongoose = require("mongoose");
const Platform = require("./models/Platform");
const User = require("./models/User");
require("dotenv").config();

const seedPlatforms = [
  // Programming Category (8 platforms)
  {
    name: "CodeMaster",
    description: "Learn programming, DSA, and system design with structured courses.",
    category: "Programming",
    type: "Freemium",
    level: "Beginner",
    website: "https://codemaster.com",
    averageRating: 4.5,
    totalReviews: 32,
  },
  {
    name: "AlgoExpert Hub",
    description: "Advanced coding interview preparation with real-world problems.",
    category: "Programming",
    type: "Paid",
    level: "Advanced",
    website: "https://algoexpert.io",
    averageRating: 4.7,
    totalReviews: 28,
  },
  {
    name: "WebDev Academy",
    description: "Complete web development course from basics to advanced projects.",
    category: "Programming",
    type: "Freemium",
    level: "Intermediate",
    website: "https://webdevacademy.com",
    averageRating: 4.3,
    totalReviews: 41,
  },
  {
    name: "PyMastery",
    description: "Master Python programming from fundamentals to data science applications.",
    category: "Programming",
    type: "Free",
    level: "Beginner",
    website: "https://pymastery.com",
    averageRating: 4.4,
    totalReviews: 37,
  },
  {
    name: "JavaSpring Boot",
    description: "Enterprise Java development and Spring Boot microservices training.",
    category: "Programming",
    type: "Paid",
    level: "Advanced",
    website: "https://javaspringboot.com",
    averageRating: 4.6,
    totalReviews: 22,
  },
  {
    name: "ReactLab",
    description: "Modern React development with hooks, state management, and performance optimization.",
    category: "Programming",
    type: "Freemium",
    level: "Intermediate",
    website: "https://reactlab.com",
    averageRating: 4.5,
    totalReviews: 38,
  },
  {
    name: "DevOps Academy",
    description: "Complete guide to DevOps, Docker, Kubernetes, and cloud deployment.",
    category: "Programming",
    type: "Paid",
    level: "Advanced",
    website: "https://devopsacademy.com",
    averageRating: 4.2,
    totalReviews: 19,
  },
  {
    name: "Mobile Dev Hub",
    description: "iOS and Android app development for beginners and intermediate developers.",
    category: "Programming",
    type: "Freemium",
    level: "Intermediate",
    website: "https://mobiledevhub.com",
    averageRating: 4.1,
    totalReviews: 25,
  },

  // Competitive Exams Category (8 platforms)
  {
    name: "ExamPro",
    description: "Prepare for government and competitive exams with mock tests.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Intermediate",
    website: "https://exampro.com",
    averageRating: 4.6,
    totalReviews: 45,
  },
  {
    name: "PrepMaster",
    description: "Daily quizzes and exam preparation materials for all major exams.",
    category: "Competitive Exams",
    type: "Freemium",
    level: "Beginner",
    website: "https://prepmaster.com",
    averageRating: 4.3,
    totalReviews: 52,
  },
  {
    name: "GateCoach",
    description: "Specialized coaching for GATE exams with doubt solving.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Advanced",
    website: "https://gatecoach.com",
    averageRating: 4.7,
    totalReviews: 38,
  },
  {
    name: "IAS Success",
    description: "Comprehensive IAS and UPSC exam preparation with live classes and mentoring.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Advanced",
    website: "https://iassuccess.com",
    averageRating: 4.5,
    totalReviews: 48,
  },
  {
    name: "SSC Quest",
    description: "Focused SSC exam preparation with topic-wise tests and detailed solutions.",
    category: "Competitive Exams",
    type: "Freemium",
    level: "Intermediate",
    website: "https://sscquest.com",
    averageRating: 4.2,
    totalReviews: 35,
  },
  {
    name: "Banking Pro",
    description: "Targeted preparation for banking and insurance competitive exams.",
    category: "Competitive Exams",
    type: "Freemium",
    level: "Intermediate",
    website: "https://bankingpro.com",
    averageRating: 4.4,
    totalReviews: 29,
  },
  {
    name: "CAT Master",
    description: "MBA entrance exam CAT with advanced problem-solving strategies.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Advanced",
    website: "https://catmaster.com",
    averageRating: 4.8,
    totalReviews: 21,
  },
  {
    name: "Aptitude Lab",
    description: "Quantitative aptitude and logical reasoning for all competitive exams.",
    category: "Competitive Exams",
    type: "Free",
    level: "Beginner",
    website: "https://aptitudelab.com",
    averageRating: 4.0,
    totalReviews: 31,
  },

  // School Learning Category (8 platforms)
  {
    name: "SmartSchool",
    description: "Interactive learning platform for school students with video lessons.",
    category: "School Learning",
    type: "Free",
    level: "Beginner",
    website: "https://smartschool.com",
    averageRating: 4.2,
    totalReviews: 44,
  },
  {
    name: "EduKids",
    description: "Gamified learning platform for children and school students.",
    category: "School Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://edukids.com",
    averageRating: 4.3,
    totalReviews: 39,
  },
  {
    name: "SchoolPlus",
    description: "Comprehensive school curriculum with study materials and notes.",
    category: "School Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://schoolplus.com",
    averageRating: 4.1,
    totalReviews: 36,
  },
  {
    name: "MathMaster",
    description: "Interactive mathematics learning with visual concepts and practice problems.",
    category: "School Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://mathmaster.com",
    averageRating: 4.4,
    totalReviews: 27,
  },
  {
    name: "ScienceHub",
    description: "Science concepts with 3D simulations and lab experiments for school students.",
    category: "School Learning",
    type: "Free",
    level: "Beginner",
    website: "https://sciencehub.com",
    averageRating: 4.3,
    totalReviews: 34,
  },
  {
    name: "HistoryVault",
    description: "Historical events with timelines, documentaries, and interactive maps.",
    category: "School Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://historyvault.com",
    averageRating: 4.0,
    totalReviews: 20,
  },
  {
    name: "NCERT Plus",
    description: "NCERT curriculum coverage with board exam preparation and solutions.",
    category: "School Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://ncertplus.com",
    averageRating: 4.5,
    totalReviews: 50,
  },
  {
    name: "LiteraryLearn",
    description: "English literature with book summaries, analysis, and essay writing guides.",
    category: "School Learning",
    type: "Free",
    level: "Beginner",
    website: "https://literarylearn.com",
    averageRating: 3.9,
    totalReviews: 18,
  },

  // College Resources Category (8 platforms)
  {
    name: "CampusConnect",
    description: "Platform for accessing college resources, notes, and announcements.",
    category: "College Resources",
    type: "Free",
    level: "Intermediate",
    website: "https://campusconnect.com",
    averageRating: 4.1,
    totalReviews: 26,
  },
  {
    name: "UniHub",
    description: "All-in-one college portal for assignments, notes, and collaboration.",
    category: "College Resources",
    type: "Freemium",
    level: "Intermediate",
    website: "https://unihub.com",
    averageRating: 4.2,
    totalReviews: 33,
  },
  {
    name: "AcademicPro",
    description: "Advanced research resources and academic materials for college students.",
    category: "College Resources",
    type: "Paid",
    level: "Advanced",
    website: "https://academicpro.com",
    averageRating: 4.6,
    totalReviews: 24,
  },
  {
    name: "ProjectLab",
    description: "Guidance and resources for college projects, assignments, and capstone work.",
    category: "College Resources",
    type: "Freemium",
    level: "Advanced",
    website: "https://projectlab.com",
    averageRating: 4.3,
    totalReviews: 28,
  },
  {
    name: "LibraryVault",
    description: "Digital library with research papers, journals, and academic databases.",
    category: "College Resources",
    type: "Paid",
    level: "Advanced",
    website: "https://libraryvault.com",
    averageRating: 4.5,
    totalReviews: 19,
  },
  {
    name: "NotesHub",
    description: "Crowdsourced notes from college students across various universities.",
    category: "College Resources",
    type: "Free",
    level: "Intermediate",
    website: "https://noteshub.com",
    averageRating: 3.8,
    totalReviews: 42,
  },
  {
    name: "StudyGroup Pro",
    description: "Study group formation and collaboration tools for college students.",
    category: "College Resources",
    type: "Freemium",
    level: "Intermediate",
    website: "https://studygrouppro.com",
    averageRating: 4.0,
    totalReviews: 22,
  },
  {
    name: "GradeBooster",
    description: "Academic guidance and tutoring service for improving college performance.",
    category: "College Resources",
    type: "Paid",
    level: "Advanced",
    website: "https://gradebooster.com",
    averageRating: 4.4,
    totalReviews: 30,
  },

  // Skill Development Category (8 platforms)
  {
    name: "SkillBoost",
    description: "Learn industry skills like communication, leadership, and productivity.",
    category: "Skill Development",
    type: "Freemium",
    level: "Beginner",
    website: "https://skillboost.com",
    averageRating: 4.3,
    totalReviews: 35,
  },
  {
    name: "CareerUp",
    description: "Professional development courses for career growth and job readiness.",
    category: "Skill Development",
    type: "Paid",
    level: "Advanced",
    website: "https://careerup.com",
    averageRating: 4.5,
    totalReviews: 27,
  },
  {
    name: "TalentHub",
    description: "Marketplace for learning soft skills and professional certifications.",
    category: "Skill Development",
    type: "Freemium",
    level: "Intermediate",
    website: "https://talenthub.com",
    averageRating: 4.2,
    totalReviews: 40,
  },
  {
    name: "LeadershipAcademy",
    description: "Executive and leadership training for career advancement and management.",
    category: "Skill Development",
    type: "Paid",
    level: "Advanced",
    website: "https://leadershipacademy.com",
    averageRating: 4.6,
    totalReviews: 23,
  },
  {
    name: "DigitalMarketing Pro",
    description: "Digital marketing, SEO, social media, and content creation skills.",
    category: "Skill Development",
    type: "Freemium",
    level: "Intermediate",
    website: "https://digitalmarketingpro.com",
    averageRating: 4.4,
    totalReviews: 38,
  },
  {
    name: "CommunicationSkills",
    description: "Public speaking, presentation, and interpersonal communication training.",
    category: "Skill Development",
    type: "Free",
    level: "Beginner",
    website: "https://communicationskills.com",
    averageRating: 4.1,
    totalReviews: 31,
  },
  {
    name: "FinanceGenius",
    description: "Financial literacy, investment, and personal finance management skills.",
    category: "Skill Development",
    type: "Freemium",
    level: "Intermediate",
    website: "https://financegenius.com",
    averageRating: 4.3,
    totalReviews: 29,
  },
  {
    name: "EntrepreneurHub",
    description: "Startup skills, business planning, and entrepreneurship development program.",
    category: "Skill Development",
    type: "Paid",
    level: "Advanced",
    website: "https://entrepreneurhub.com",
    averageRating: 4.5,
    totalReviews: 16,
  },

  // Language Learning Category (8 platforms)
  {
    name: "LinguaLearn",
    description: "Learn new languages with interactive lessons and practice exercises.",
    category: "Language Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://lingualearn.com",
    averageRating: 4.4,
    totalReviews: 43,
  },
  {
    name: "SpeakEasy",
    description: "Improve speaking and communication skills in multiple languages.",
    category: "Language Learning",
    type: "Paid",
    level: "Intermediate",
    website: "https://speakeasy.com",
    averageRating: 4.6,
    totalReviews: 34,
  },
  {
    name: "PolyGlot Pro",
    description: "Advanced language learning with culture immersion and native tutors.",
    category: "Language Learning",
    type: "Paid",
    level: "Advanced",
    website: "https://polyglotpro.com",
    averageRating: 4.8,
    totalReviews: 25,
  },
  {
    name: "SpanishMaster",
    description: "Specialized Spanish learning from beginner to advanced fluency.",
    category: "Language Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://spanishmaster.com",
    averageRating: 4.3,
    totalReviews: 36,
  },
  {
    name: "MandarinEase",
    description: "Mandarin Chinese learning with pinyin, characters, and conversation practice.",
    category: "Language Learning",
    type: "Paid",
    level: "Intermediate",
    website: "https://mandarinease.com",
    averageRating: 4.2,
    totalReviews: 20,
  },
  {
    name: "GermanFluency",
    description: "German language mastery with grammar, vocabulary, and cultural insights.",
    category: "Language Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://germanfluency.com",
    averageRating: 4.1,
    totalReviews: 28,
  },
  {
    name: "JapaneseStep",
    description: "Learn Japanese hiragana, katakana, kanji with native speaker interactions.",
    category: "Language Learning",
    type: "Paid",
    level: "Advanced",
    website: "https://japanesestep.com",
    averageRating: 4.5,
    totalReviews: 17,
  },
  {
    name: "FrenchConnect",
    description: "French language learning with pronunciation, grammar, and cultural context.",
    category: "Language Learning",
    type: "Free",
    level: "Beginner",
    website: "https://frenchconnect.com",
    averageRating: 3.9,
    totalReviews: 32,
  },

  // Entertainment Category (11 platforms)
  {
    name: "Netflix",
    description: "Streaming platform for movies, TV series, and documentaries worldwide.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://netflix.com",
    averageRating: 4.7,
    totalReviews: 156,
  },
  {
    name: "Amazon Prime Video",
    description: "Comprehensive streaming service with movies, shows, and exclusive content.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://primevideo.com",
    averageRating: 4.6,
    totalReviews: 142,
  },
  {
    name: "Disney+",
    description: "Family-friendly streaming with Disney, Pixar, Marvel, and Star Wars content.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://disneyplus.com",
    averageRating: 4.8,
    totalReviews: 128,
  },
  {
    name: "HBO Max",
    description: "Premium streaming service with HBO series, movies, and Warner Bros. films.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://hbomax.com",
    averageRating: 4.7,
    totalReviews: 119,
  },
  {
    name: "Spotify",
    description: "Music streaming platform with podcasts, playlists, and audio content.",
    category: "Entertainment",
    type: "Freemium",
    level: "Beginner",
    website: "https://spotify.com",
    averageRating: 4.6,
    totalReviews: 178,
  },
  {
    name: "YouTube Premium",
    description: "Ad-free video streaming, offline viewing, and background play capabilities.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://youtube.com/premium",
    averageRating: 4.5,
    totalReviews: 165,
  },
  {
    name: "Twitch",
    description: "Live streaming platform for gaming, creative content, and interactive entertainment.",
    category: "Entertainment",
    type: "Freemium",
    level: "Intermediate",
    website: "https://twitch.tv",
    averageRating: 4.4,
    totalReviews: 134,
  },
  {
    name: "Apple TV+",
    description: "Original series and films featuring exclusive Apple content and productions.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://tv.apple.com",
    averageRating: 4.6,
    totalReviews: 98,
  },
  {
    name: "Peacock",
    description: "NBC's streaming service with movies, shows, sports, and original programs.",
    category: "Entertainment",
    type: "Freemium",
    level: "Beginner",
    website: "https://peacocktv.com",
    averageRating: 4.3,
    totalReviews: 87,
  },
  {
    name: "Hulu",
    description: "Streaming service offering next-day episodes, original series, and movies.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://hulu.com",
    averageRating: 4.5,
    totalReviews: 121,
  },
  {
    name: "Paramount+",
    description: "Streaming platform with CBS, movies, sports, and exclusive Paramount content.",
    category: "Entertainment",
    type: "Subscription",
    level: "Beginner",
    website: "https://paramountplus.com",
    averageRating: 4.4,
    totalReviews: 105,
  },

  // Finance Category (11 platforms)
  {
    name: "Robinhood",
    description: "Zero-commission stock trading and investment app for beginners and experts.",
    category: "Finance",
    type: "Free",
    level: "Beginner",
    website: "https://robinhood.com",
    averageRating: 4.3,
    totalReviews: 145,
  },
  {
    name: "E-TRADE",
    description: "Full-service broker with stocks, options, mutual funds, and retirement accounts.",
    category: "Finance",
    type: "Freemium",
    level: "Intermediate",
    website: "https://etrade.com",
    averageRating: 4.5,
    totalReviews: 132,
  },
  {
    name: "Fidelity Investments",
    description: "Comprehensive financial services including brokerage, retirement, and banking.",
    category: "Finance",
    type: "Freemium",
    level: "Advanced",
    website: "https://fidelity.com",
    averageRating: 4.7,
    totalReviews: 167,
  },
  {
    name: "Vanguard",
    description: "Investment management and financial advisory with low-cost funds.",
    category: "Finance",
    type: "Paid",
    level: "Advanced",
    website: "https://vanguard.com",
    averageRating: 4.6,
    totalReviews: 148,
  },
  {
    name: "Coinbase",
    description: "Cryptocurrency trading platform for buying, selling, and staking digital assets.",
    category: "Finance",
    type: "Freemium",
    level: "Intermediate",
    website: "https://coinbase.com",
    averageRating: 4.2,
    totalReviews: 156,
  },
  {
    name: "PayPal",
    description: "Digital payment platform for transfers, online shopping, and merchant services.",
    category: "Finance",
    type: "Free",
    level: "Beginner",
    website: "https://paypal.com",
    averageRating: 4.4,
    totalReviews: 189,
  },
  {
    name: "Square Cash",
    description: "Fast peer-to-peer payment app for sending money and managing finances.",
    category: "Finance",
    type: "Free",
    level: "Beginner",
    website: "https://cash.app",
    averageRating: 4.3,
    totalReviews: 127,
  },
  {
    name: "Personal Capital",
    description: "Wealth management and financial planning app with investment tracking tools.",
    category: "Finance",
    type: "Freemium",
    level: "Advanced",
    website: "https://personalcapital.com",
    averageRating: 4.5,
    totalReviews: 98,
  },
  {
    name: "Mint",
    description: "Financial tracking and budgeting app to manage spending and savings goals.",
    category: "Finance",
    type: "Free",
    level: "Beginner",
    website: "https://mint.com",
    averageRating: 4.4,
    totalReviews: 112,
  },
  {
    name: "Interactive Brokers",
    description: "Advanced trading platform with stocks, options, futures, and forex markets.",
    category: "Finance",
    type: "Paid",
    level: "Advanced",
    website: "https://interactivebrokers.com",
    averageRating: 4.6,
    totalReviews: 87,
  },
  {
    name: "Acorns",
    description: "Micro-investing app that rounds up purchases and invests automatically.",
    category: "Finance",
    type: "Paid",
    level: "Beginner",
    website: "https://acorns.com",
    averageRating: 4.3,
    totalReviews: 115,
  },

  // E-commerce Category (11 platforms)
  {
    name: "Amazon",
    description: "World's largest online marketplace for products, electronics, and essentials.",
    category: "E-commerce",
    type: "Free",
    level: "Beginner",
    website: "https://amazon.com",
    averageRating: 4.6,
    totalReviews: 287,
  },
  {
    name: "eBay",
    description: "Online auction and marketplace platform for buying and selling items.",
    category: "E-commerce",
    type: "Free",
    level: "Beginner",
    website: "https://ebay.com",
    averageRating: 4.4,
    totalReviews: 198,
  },
  {
    name: "Shopify",
    description: "E-commerce platform for creating and managing online stores and businesses.",
    category: "E-commerce",
    type: "Paid",
    level: "Intermediate",
    website: "https://shopify.com",
    averageRating: 4.7,
    totalReviews: 156,
  },
  {
    name: "Etsy",
    description: "Marketplace for handmade, vintage, and unique items from independent sellers.",
    category: "E-commerce",
    type: "Freemium",
    level: "Beginner",
    website: "https://etsy.com",
    averageRating: 4.5,
    totalReviews: 167,
  },
  {
    name: "Walmart Online",
    description: "Retail giant's e-commerce platform with groceries, electronics, and home goods.",
    category: "E-commerce",
    type: "Free",
    level: "Beginner",
    website: "https://walmart.com",
    averageRating: 4.3,
    totalReviews: 134,
  },
  {
    name: "AliExpress",
    description: "Global online marketplace connecting Chinese manufacturers with international buyers.",
    category: "E-commerce",
    type: "Free",
    level: "Intermediate",
    website: "https://aliexpress.com",
    averageRating: 4.2,
    totalReviews: 145,
  },
  {
    name: "Flipkart",
    description: "India's largest e-commerce platform for electronics, fashion, and daily needs.",
    category: "E-commerce",
    type: "Free",
    level: "Beginner",
    website: "https://flipkart.com",
    averageRating: 4.4,
    totalReviews: 178,
  },
  {
    name: "WooCommerce",
    description: "WordPress-based e-commerce plugin for building customizable online stores.",
    category: "E-commerce",
    type: "Free",
    level: "Intermediate",
    website: "https://woocommerce.com",
    averageRating: 4.6,
    totalReviews: 112,
  },
  {
    name: "BigCommerce",
    description: "Enterprise e-commerce platform for scaling online retail businesses.",
    category: "E-commerce",
    type: "Paid",
    level: "Advanced",
    website: "https://bigcommerce.com",
    averageRating: 4.6,
    totalReviews: 98,
  },
  {
    name: "Mercado Libre",
    description: "Latin America's largest e-commerce marketplace for diverse products.",
    category: "E-commerce",
    type: "Free",
    level: "Beginner",
    website: "https://mercadolibre.com",
    averageRating: 4.3,
    totalReviews: 124,
  },
  {
    name: "Shein",
    description: "Fast fashion e-commerce platform offering trendy clothing and accessories.",
    category: "E-commerce",
    type: "Free",
    level: "Beginner",
    website: "https://shein.com",
    averageRating: 4.2,
    totalReviews: 156,
  },

  // Social Media Category (11 platforms)
  {
    name: "Facebook",
    description: "Global social network for connecting with friends, family, and communities.",
    category: "Social Media",
    type: "Free",
    level: "Beginner",
    website: "https://facebook.com",
    averageRating: 4.1,
    totalReviews: 247,
  },
  {
    name: "Instagram",
    description: "Photo and video sharing platform focused on visual storytelling and influencers.",
    category: "Social Media",
    type: "Free",
    level: "Beginner",
    website: "https://instagram.com",
    averageRating: 4.3,
    totalReviews: 198,
  },
  {
    name: "Twitter/X",
    description: "Microblogging platform for sharing thoughts, news, and engaging in conversations.",
    category: "Social Media",
    type: "Freemium",
    level: "Beginner",
    website: "https://twitter.com",
    averageRating: 4.0,
    totalReviews: 187,
  },
  {
    name: "TikTok",
    description: "Short-form video platform for entertaining, creative, and viral content.",
    category: "Social Media",
    type: "Free",
    level: "Beginner",
    website: "https://tiktok.com",
    averageRating: 4.4,
    totalReviews: 221,
  },
  {
    name: "LinkedIn",
    description: "Professional networking platform for career development and business connections.",
    category: "Social Media",
    type: "Freemium",
    level: "Intermediate",
    website: "https://linkedin.com",
    averageRating: 4.5,
    totalReviews: 156,
  },
  {
    name: "YouTube",
    description: "Video sharing platform for streaming, uploading, and discovering video content.",
    category: "Social Media",
    type: "Free",
    level: "Beginner",
    website: "https://youtube.com",
    averageRating: 4.6,
    totalReviews: 267,
  },
  {
    name: "Reddit",
    description: "Community-driven platform with forums (subreddits) for discussions and content.",
    category: "Social Media",
    type: "Free",
    level: "Intermediate",
    website: "https://reddit.com",
    averageRating: 4.2,
    totalReviews: 134,
  },
  {
    name: "Snapchat",
    description: "Messaging app featuring disappearing photos, stories, and video content.",
    category: "Social Media",
    type: "Free",
    level: "Beginner",
    website: "https://snapchat.com",
    averageRating: 4.1,
    totalReviews: 127,
  },
  {
    name: "Pinterest",
    description: "Visual discovery platform for sharing and bookmarking ideas and inspirations.",
    category: "Social Media",
    type: "Freemium",
    level: "Beginner",
    website: "https://pinterest.com",
    averageRating: 4.3,
    totalReviews: 142,
  },
  {
    name: "Discord",
    description: "Community server platform for voice, video, and text communication.",
    category: "Social Media",
    type: "Free",
    level: "Intermediate",
    website: "https://discord.com",
    averageRating: 4.7,
    totalReviews: 165,
  },
  {
    name: "Telegram",
    description: "Encrypted messaging app with channels, groups, and privacy-focused features.",
    category: "Social Media",
    type: "Free",
    level: "Beginner",
    website: "https://telegram.org",
    averageRating: 4.5,
    totalReviews: 119,
  },

  // Productivity Category (11 platforms)
  {
    name: "Notion",
    description: "All-in-one workspace for notes, databases, wikis, and project management.",
    category: "Productivity",
    type: "Freemium",
    level: "Intermediate",
    website: "https://notion.so",
    averageRating: 4.6,
    totalReviews: 178,
  },
  {
    name: "Asana",
    description: "Team project management tool for tracking tasks, deadlines, and workflows.",
    category: "Productivity",
    type: "Freemium",
    level: "Intermediate",
    website: "https://asana.com",
    averageRating: 4.5,
    totalReviews: 145,
  },
  {
    name: "Monday.com",
    description: "Visual work operating system for project and team management.",
    category: "Productivity",
    type: "Freemium",
    level: "Intermediate",
    website: "https://monday.com",
    averageRating: 4.6,
    totalReviews: 132,
  },
  {
    name: "Trello",
    description: "Kanban-based project management tool with cards, boards, and lists.",
    category: "Productivity",
    type: "Freemium",
    level: "Beginner",
    website: "https://trello.com",
    averageRating: 4.4,
    totalReviews: 156,
  },
  {
    name: "Jira",
    description: "Software project management tool for agile development and issue tracking.",
    category: "Productivity",
    type: "Paid",
    level: "Advanced",
    website: "https://jira.com",
    averageRating: 4.7,
    totalReviews: 134,
  },
  {
    name: "Slack",
    description: "Team communication platform with messaging, channels, and integrations.",
    category: "Productivity",
    type: "Freemium",
    level: "Beginner",
    website: "https://slack.com",
    averageRating: 4.5,
    totalReviews: 167,
  },
  {
    name: "Microsoft Teams",
    description: "Unified workplace with chat, video, meetings, and file collaboration.",
    category: "Productivity",
    type: "Freemium",
    level: "Intermediate",
    website: "https://teams.microsoft.com",
    averageRating: 4.4,
    totalReviews: 148,
  },
  {
    name: "Todoist",
    description: "Task management and to-do list app for organizing personal and work projects.",
    category: "Productivity",
    type: "Freemium",
    level: "Beginner",
    website: "https://todoist.com",
    averageRating: 4.6,
    totalReviews: 121,
  },
  {
    name: "Google Workspace",
    description: "Cloud-based suite with Gmail, Docs, Sheets, Slides, and Drive collaboration.",
    category: "Productivity",
    type: "Paid",
    level: "Intermediate",
    website: "https://workspace.google.com",
    averageRating: 4.7,
    totalReviews: 189,
  },
  {
    name: "Evernote",
    description: "Digital note-taking app for capturing, organizing, and syncing information.",
    category: "Productivity",
    type: "Freemium",
    level: "Beginner",
    website: "https://evernote.com",
    averageRating: 4.3,
    totalReviews: 112,
  },
  {
    name: "ClickUp",
    description: "Comprehensive productivity platform combining tasks, docs, and communication.",
    category: "Productivity",
    type: "Freemium",
    level: "Advanced",
    website: "https://clickup.com",
    averageRating: 4.5,
    totalReviews: 98,
  },

  // Health & Fitness Category (11 platforms)
  {
    name: "MyFitnessPal",
    description: "Fitness and nutrition tracking app with workout logging and calorie counter.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Beginner",
    website: "https://myfitnesspal.com",
    averageRating: 4.4,
    totalReviews: 187,
  },
  {
    name: "Peloton",
    description: "Connected fitness platform with live and on-demand workout classes.",
    category: "Health & Fitness",
    type: "Subscription",
    level: "Intermediate",
    website: "https://peloton.com",
    averageRating: 4.6,
    totalReviews: 156,
  },
  {
    name: "Fitbit",
    description: "Wearable fitness tracker for monitoring activity, heart rate, and sleep.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Beginner",
    website: "https://fitbit.com",
    averageRating: 4.5,
    totalReviews: 145,
  },
  {
    name: "Calm",
    description: "Meditation and mindfulness app with sleep stories and relaxation programs.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Beginner",
    website: "https://calm.com",
    averageRating: 4.7,
    totalReviews: 198,
  },
  {
    name: "Headspace",
    description: "Guided meditation and mindfulness training for mental wellness and stress relief.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Beginner",
    website: "https://headspace.com",
    averageRating: 4.6,
    totalReviews: 167,
  },
  {
    name: "Strava",
    description: "Social fitness app for runners and cyclists to track and share activities.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Intermediate",
    website: "https://strava.com",
    averageRating: 4.5,
    totalReviews: 134,
  },
  {
    name: "Apple Health",
    description: "Comprehensive health data repository for tracking fitness, health, and wellness.",
    category: "Health & Fitness",
    type: "Free",
    level: "Beginner",
    website: "https://apple.com/health",
    averageRating: 4.4,
    totalReviews: 121,
  },
  {
    name: "Yoga with Adriene",
    description: "Online yoga platform with guided video classes for all skill levels.",
    category: "Health & Fitness",
    type: "Free",
    level: "Beginner",
    website: "https://yogawithadriene.com",
    averageRating: 4.6,
    totalReviews: 142,
  },
  {
    name: "Nike Training Club",
    description: "Workout app with diverse training programs from beginners to advanced athletes.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Intermediate",
    website: "https://nike.com/training-club",
    averageRating: 4.5,
    totalReviews: 128,
  },
  {
    name: "Teladoc",
    description: "Telehealth platform connecting with doctors and healthcare professionals.",
    category: "Health & Fitness",
    type: "Paid",
    level: "Intermediate",
    website: "https://teladoc.com",
    averageRating: 4.3,
    totalReviews: 97,
  },
  {
    name: "Adidas Running",
    description: "Running tracker app with training plans, audio coaching, and community features.",
    category: "Health & Fitness",
    type: "Freemium",
    level: "Intermediate",
    website: "https://adidasruntastic.com",
    averageRating: 4.4,
    totalReviews: 115,
  },

  // Travel Category (11 platforms)
  {
    name: "Booking.com",
    description: "Hotel and accommodation booking platform with competitive pricing worldwide.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://booking.com",
    averageRating: 4.5,
    totalReviews: 267,
  },
  {
    name: "Airbnb",
    description: "Peer-to-peer accommodation sharing platform for unique travel experiences.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://airbnb.com",
    averageRating: 4.6,
    totalReviews: 245,
  },
  {
    name: "Expedia",
    description: "Travel booking platform for flights, hotels, cars, and vacation packages.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://expedia.com",
    averageRating: 4.4,
    totalReviews: 189,
  },
  {
    name: "Google Flights",
    description: "Flight search and comparison tool with price tracking and flexible dates.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://flights.google.com",
    averageRating: 4.6,
    totalReviews: 156,
  },
  {
    name: "TripAdvisor",
    description: "Travel information platform with reviews, recommendations, and booking options.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://tripadvisor.com",
    averageRating: 4.3,
    totalReviews: 178,
  },
  {
    name: "Uber",
    description: "Ride-sharing platform for transportation and mobility in cities worldwide.",
    category: "Travel",
    type: "Freemium",
    level: "Beginner",
    website: "https://uber.com",
    averageRating: 4.2,
    totalReviews: 198,
  },
  {
    name: "Skyscanner",
    description: "Flight, hotel, and rental car comparison platform for finding best deals.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://skyscanner.com",
    averageRating: 4.5,
    totalReviews: 145,
  },
  {
    name: "GetYourGuide",
    description: "Platform for booking tours, attractions, and activities worldwide.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://getyourguide.com",
    averageRating: 4.4,
    totalReviews: 128,
  },
  {
    name: "Viator",
    description: "Tour and experience booking platform from TripAdvisor for unique activities.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://viator.com",
    averageRating: 4.3,
    totalReviews: 112,
  },
  {
    name: "Kayak",
    description: "Travel search engine comparing flights, hotels, and car rentals instantly.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://kayak.com",
    averageRating: 4.4,
    totalReviews: 134,
  },
  {
    name: "Hostelworld",
    description: "Hostel booking platform for budget travelers and backpackers worldwide.",
    category: "Travel",
    type: "Free",
    level: "Beginner",
    website: "https://hostelworld.com",
    averageRating: 4.2,
    totalReviews: 98,
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    // Seed admin user
    await User.deleteMany({ role: "admin" });
    const adminUser = new User({
      username: "admin",
      email: "admin@platform.com",
      password: "admin123456",
      role: "admin",
      isAdmin: true,
    });
    await adminUser.save();
    console.log("✅ Admin user created: admin@platform.com (password: admin123456)");

    // Seed platforms
    await Platform.deleteMany({});
    console.log("Cleared existing platforms");

    const inserted = await Platform.insertMany(seedPlatforms, { ordered: false });
    console.log(`${inserted.length} platforms inserted successfully`);

    await mongoose.connection.close();
    console.log("Seeding completed");
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
};

seedDatabase();
