const mongoose = require("mongoose");
const Platform = require("./models/Platform");
const User = require("./models/User");
require("dotenv").config();

const seedPlatforms = [
  // Programming Category (8 platforms)
  {
    name: "CodeMaster",
    description: "Learn programming, DSA, and system design with structured courses.",
    category: "Programming",
    type: "Freemium",
    level: "Beginner",
    website: "https://codemaster.com",
    averageRating: 4.5,
    totalReviews: 32,
  },
  {
    name: "AlgoExpert Hub",
    description: "Advanced coding interview preparation with real-world problems.",
    category: "Programming",
    type: "Paid",
    level: "Advanced",
    website: "https://algoexpert.io",
    averageRating: 4.7,
    totalReviews: 28,
  },
  {
    name: "WebDev Academy",
    description: "Complete web development course from basics to advanced projects.",
    category: "Programming",
    type: "Freemium",
    level: "Intermediate",
    website: "https://webdevacademy.com",
    averageRating: 4.3,
    totalReviews: 41,
  },
  {
    name: "PyMastery",
    description: "Master Python programming from fundamentals to data science applications.",
    category: "Programming",
    type: "Free",
    level: "Beginner",
    website: "https://pymastery.com",
    averageRating: 4.4,
    totalReviews: 37,
  },
  {
    name: "JavaSpring Boot",
    description: "Enterprise Java development and Spring Boot microservices training.",
    category: "Programming",
    type: "Paid",
    level: "Advanced",
    website: "https://javaspringboot.com",
    averageRating: 4.6,
    totalReviews: 22,
  },
  {
    name: "ReactLab",
    description: "Modern React development with hooks, state management, and performance optimization.",
    category: "Programming",
    type: "Freemium",
    level: "Intermediate",
    website: "https://reactlab.com",
    averageRating: 4.5,
    totalReviews: 38,
  },
  {
    name: "DevOps Academy",
    description: "Complete guide to DevOps, Docker, Kubernetes, and cloud deployment.",
    category: "Programming",
    type: "Paid",
    level: "Advanced",
    website: "https://devopsacademy.com",
    averageRating: 4.2,
    totalReviews: 19,
  },
  {
    name: "Mobile Dev Hub",
    description: "iOS and Android app development for beginners and intermediate developers.",
    category: "Programming",
    type: "Freemium",
    level: "Intermediate",
    website: "https://mobiledevhub.com",
    averageRating: 4.1,
    totalReviews: 25,
  },

  // Competitive Exams Category (8 platforms)
  {
    name: "ExamPro",
    description: "Prepare for government and competitive exams with mock tests.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Intermediate",
    website: "https://exampro.com",
    averageRating: 4.6,
    totalReviews: 45,
  },
  {
    name: "PrepMaster",
    description: "Daily quizzes and exam preparation materials for all major exams.",
    category: "Competitive Exams",
    type: "Freemium",
    level: "Beginner",
    website: "https://prepmaster.com",
    averageRating: 4.3,
    totalReviews: 52,
  },
  {
    name: "GateCoach",
    description: "Specialized coaching for GATE exams with doubt solving.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Advanced",
    website: "https://gatecoach.com",
    averageRating: 4.7,
    totalReviews: 38,
  },
  {
    name: "IAS Success",
    description: "Comprehensive IAS and UPSC exam preparation with live classes and mentoring.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Advanced",
    website: "https://iassuccess.com",
    averageRating: 4.5,
    totalReviews: 48,
  },
  {
    name: "SSC Quest",
    description: "Focused SSC exam preparation with topic-wise tests and detailed solutions.",
    category: "Competitive Exams",
    type: "Freemium",
    level: "Intermediate",
    website: "https://sscquest.com",
    averageRating: 4.2,
    totalReviews: 35,
  },
  {
    name: "Banking Pro",
    description: "Targeted preparation for banking and insurance competitive exams.",
    category: "Competitive Exams",
    type: "Freemium",
    level: "Intermediate",
    website: "https://bankingpro.com",
    averageRating: 4.4,
    totalReviews: 29,
  },
  {
    name: "CAT Master",
    description: "MBA entrance exam CAT with advanced problem-solving strategies.",
    category: "Competitive Exams",
    type: "Paid",
    level: "Advanced",
    website: "https://catmaster.com",
    averageRating: 4.8,
    totalReviews: 21,
  },
  {
    name: "Aptitude Lab",
    description: "Quantitative aptitude and logical reasoning for all competitive exams.",
    category: "Competitive Exams",
    type: "Free",
    level: "Beginner",
    website: "https://aptitudelab.com",
    averageRating: 4.0,
    totalReviews: 31,
  },

  // School Learning Category (8 platforms)
  {
    name: "SmartSchool",
    description: "Interactive learning platform for school students with video lessons.",
    category: "School Learning",
    type: "Free",
    level: "Beginner",
    website: "https://smartschool.com",
    averageRating: 4.2,
    totalReviews: 44,
  },
  {
    name: "EduKids",
    description: "Gamified learning platform for children and school students.",
    category: "School Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://edukids.com",
    averageRating: 4.3,
    totalReviews: 39,
  },
  {
    name: "SchoolPlus",
    description: "Comprehensive school curriculum with study materials and notes.",
    category: "School Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://schoolplus.com",
    averageRating: 4.1,
    totalReviews: 36,
  },
  {
    name: "MathMaster",
    description: "Interactive mathematics learning with visual concepts and practice problems.",
    category: "School Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://mathmaster.com",
    averageRating: 4.4,
    totalReviews: 27,
  },
  {
    name: "ScienceHub",
    description: "Science concepts with 3D simulations and lab experiments for school students.",
    category: "School Learning",
    type: "Free",
    level: "Beginner",
    website: "https://sciencehub.com",
    averageRating: 4.3,
    totalReviews: 34,
  },
  {
    name: "HistoryVault",
    description: "Historical events with timelines, documentaries, and interactive maps.",
    category: "School Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://historyvault.com",
    averageRating: 4.0,
    totalReviews: 20,
  },
  {
    name: "NCERT Plus",
    description: "NCERT curriculum coverage with board exam preparation and solutions.",
    category: "School Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://ncertplus.com",
    averageRating: 4.5,
    totalReviews: 50,
  },
  {
    name: "LiteraryLearn",
    description: "English literature with book summaries, analysis, and essay writing guides.",
    category: "School Learning",
    type: "Free",
    level: "Beginner",
    website: "https://literarylearn.com",
    averageRating: 3.9,
    totalReviews: 18,
  },

  // College Resources Category (8 platforms)
  {
    name: "CampusConnect",
    description: "Platform for accessing college resources, notes, and announcements.",
    category: "College Resources",
    type: "Free",
    level: "Intermediate",
    website: "https://campusconnect.com",
    averageRating: 4.1,
    totalReviews: 26,
  },
  {
    name: "UniHub",
    description: "All-in-one college portal for assignments, notes, and collaboration.",
    category: "College Resources",
    type: "Freemium",
    level: "Intermediate",
    website: "https://unihub.com",
    averageRating: 4.2,
    totalReviews: 33,
  },
  {
    name: "AcademicPro",
    description: "Advanced research resources and academic materials for college students.",
    category: "College Resources",
    type: "Paid",
    level: "Advanced",
    website: "https://academicpro.com",
    averageRating: 4.6,
    totalReviews: 24,
  },
  {
    name: "ProjectLab",
    description: "Guidance and resources for college projects, assignments, and capstone work.",
    category: "College Resources",
    type: "Freemium",
    level: "Advanced",
    website: "https://projectlab.com",
    averageRating: 4.3,
    totalReviews: 28,
  },
  {
    name: "LibraryVault",
    description: "Digital library with research papers, journals, and academic databases.",
    category: "College Resources",
    type: "Paid",
    level: "Advanced",
    website: "https://libraryvault.com",
    averageRating: 4.5,
    totalReviews: 19,
  },
  {
    name: "NotesHub",
    description: "Crowdsourced notes from college students across various universities.",
    category: "College Resources",
    type: "Free",
    level: "Intermediate",
    website: "https://noteshub.com",
    averageRating: 3.8,
    totalReviews: 42,
  },
  {
    name: "StudyGroup Pro",
    description: "Study group formation and collaboration tools for college students.",
    category: "College Resources",
    type: "Freemium",
    level: "Intermediate",
    website: "https://studygrouppro.com",
    averageRating: 4.0,
    totalReviews: 22,
  },
  {
    name: "GradeBooster",
    description: "Academic guidance and tutoring service for improving college performance.",
    category: "College Resources",
    type: "Paid",
    level: "Advanced",
    website: "https://gradebooster.com",
    averageRating: 4.4,
    totalReviews: 30,
  },

  // Skill Development Category (8 platforms)
  {
    name: "SkillBoost",
    description: "Learn industry skills like communication, leadership, and productivity.",
    category: "Skill Development",
    type: "Freemium",
    level: "Beginner",
    website: "https://skillboost.com",
    averageRating: 4.3,
    totalReviews: 35,
  },
  {
    name: "CareerUp",
    description: "Professional development courses for career growth and job readiness.",
    category: "Skill Development",
    type: "Paid",
    level: "Advanced",
    website: "https://careerup.com",
    averageRating: 4.5,
    totalReviews: 27,
  },
  {
    name: "TalentHub",
    description: "Marketplace for learning soft skills and professional certifications.",
    category: "Skill Development",
    type: "Freemium",
    level: "Intermediate",
    website: "https://talenthub.com",
    averageRating: 4.2,
    totalReviews: 40,
  },
  {
    name: "LeadershipAcademy",
    description: "Executive and leadership training for career advancement and management.",
    category: "Skill Development",
    type: "Paid",
    level: "Advanced",
    website: "https://leadershipacademy.com",
    averageRating: 4.6,
    totalReviews: 23,
  },
  {
    name: "DigitalMarketing Pro",
    description: "Digital marketing, SEO, social media, and content creation skills.",
    category: "Skill Development",
    type: "Freemium",
    level: "Intermediate",
    website: "https://digitalmarketingpro.com",
    averageRating: 4.4,
    totalReviews: 38,
  },
  {
    name: "CommunicationSkills",
    description: "Public speaking, presentation, and interpersonal communication training.",
    category: "Skill Development",
    type: "Free",
    level: "Beginner",
    website: "https://communicationskills.com",
    averageRating: 4.1,
    totalReviews: 31,
  },
  {
    name: "FinanceGenius",
    description: "Financial literacy, investment, and personal finance management skills.",
    category: "Skill Development",
    type: "Freemium",
    level: "Intermediate",
    website: "https://financegenius.com",
    averageRating: 4.3,
    totalReviews: 29,
  },
  {
    name: "EntrepreneurHub",
    description: "Startup skills, business planning, and entrepreneurship development program.",
    category: "Skill Development",
    type: "Paid",
    level: "Advanced",
    website: "https://entrepreneurhub.com",
    averageRating: 4.5,
    totalReviews: 16,
  },

  // Language Learning Category (8 platforms)
  {
    name: "LinguaLearn",
    description: "Learn new languages with interactive lessons and practice exercises.",
    category: "Language Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://lingualearn.com",
    averageRating: 4.4,
    totalReviews: 43,
  },
  {
    name: "SpeakEasy",
    description: "Improve speaking and communication skills in multiple languages.",
    category: "Language Learning",
    type: "Paid",
    level: "Intermediate",
    website: "https://speakeasy.com",
    averageRating: 4.6,
    totalReviews: 34,
  },
  {
    name: "PolyGlot Pro",
    description: "Advanced language learning with culture immersion and native tutors.",
    category: "Language Learning",
    type: "Paid",
    level: "Advanced",
    website: "https://polyglotpro.com",
    averageRating: 4.8,
    totalReviews: 25,
  },
  {
    name: "SpanishMaster",
    description: "Specialized Spanish learning from beginner to advanced fluency.",
    category: "Language Learning",
    type: "Freemium",
    level: "Beginner",
    website: "https://spanishmaster.com",
    averageRating: 4.3,
    totalReviews: 36,
  },
  {
    name: "MandarinEase",
    description: "Mandarin Chinese learning with pinyin, characters, and conversation practice.",
    category: "Language Learning",
    type: "Paid",
    level: "Intermediate",
    website: "https://mandarinease.com",
    averageRating: 4.2,
    totalReviews: 20,
  },
  {
    name: "GermanFluency",
    description: "German language mastery with grammar, vocabulary, and cultural insights.",
    category: "Language Learning",
    type: "Freemium",
    level: "Intermediate",
    website: "https://germanfluency.com",
    averageRating: 4.1,
    totalReviews: 28,
  },
  {
    name: "JapaneseStep",
    description: "Learn Japanese hiragana, katakana, kanji with native speaker interactions.",
    category: "Language Learning",
    type: "Paid",
    level: "Advanced",
    website: "https://japanesestep.com",
    averageRating: 4.5,
    totalReviews: 17,
  },
  {
    name: "FrenchConnect",
    description: "French language learning with pronunciation, grammar, and cultural context.",
    category: "Language Learning",
    type: "Free",
    level: "Beginner",
    website: "https://frenchconnect.com",
    averageRating: 3.9,
    totalReviews: 32,
  },
];

const seedDatabase = async () => {
  try {
    await mongoose.connect(process.env.MONGO_URI);
    console.log("Connected to MongoDB");

    // Seed admin user
    await User.deleteMany({ role: "admin" });
    const adminUser = new User({
      username: "admin",
      email: "admin@platform.com",
      password: "admin123456",
      role: "admin",
      isAdmin: true,
    });
    await adminUser.save();
    console.log("✅ Admin user created: admin@platform.com (password: admin123456)");

    // Seed platforms
    await Platform.deleteMany({});
    console.log("Cleared existing platforms");

    const inserted = await Platform.insertMany(seedPlatforms);
    console.log(`${inserted.length} platforms inserted successfully`);

    await mongoose.connection.close();
    console.log("Seeding completed");
  } catch (err) {
    console.error("Seeding error:", err);
    process.exit(1);
  }
};

seedDatabase();
